/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testingcoursework;

import infopacket.InfoPacket;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author samal
 */
public class FindUsers extends javax.swing.JFrame {

    private String Username;
    /**
     * Creates new form FindUsers
     */
    public FindUsers() {
        initComponents();
    }
    
    public FindUsers(String User) {
        initComponents();
        this.Username = User;
        UpdateList(FindUsers());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListUsers = new javax.swing.JList<>();
        cbPreference = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        cmdAddFriend = new javax.swing.JButton();
        cmdBackToMain = new javax.swing.JButton();
        cmdFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListUsers);

        cbPreference.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Folk", "Rock", "Techno", "Pop", "Blues", "Jazz", "EDM", "Rapping", "Indie", "Soul", "Raggae", "Classical" }));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Find Users Using Prefences");

        cmdAddFriend.setText("Add Friend");
        cmdAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddFriendActionPerformed(evt);
            }
        });

        cmdBackToMain.setText("Back To Main Screen");
        cmdBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackToMainActionPerformed(evt);
            }
        });

        cmdFind.setText("Find");
        cmdFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdAddFriend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdBackToMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdFind, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPreference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdAddFriend)
                .addGap(18, 18, 18)
                .addComponent(cmdBackToMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackToMainActionPerformed
        try {
            new MainScreen(Username).setVisible(true);
            this.dispose();
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_cmdBackToMainActionPerformed

    private void cmdFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindActionPerformed
        UpdateList(FindUsers());
    }//GEN-LAST:event_cmdFindActionPerformed

    private void cmdAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddFriendActionPerformed
                                                             
        try {
            
            InfoPacket FriendRequest = new InfoPacket();
            //GET MY FRIENDS
            FriendRequest.SetService("NFR");
            ArrayList<String> Users = new ArrayList();
            Users.add(Username);
            Users.add(ListUsers.getSelectedValue());
            //FriendRequest.SetSingleData(Username);
            FriendRequest.SetArray(Users);
        
            Socket MainServer = new Socket("localhost", 9090);

            ObjectOutputStream OutToServer = new ObjectOutputStream(MainServer.getOutputStream());
            ObjectInputStream FromServerStream = new ObjectInputStream(MainServer.getInputStream());

            OutToServer.writeObject(FriendRequest);

            InfoPacket ServerReply = (InfoPacket) FromServerStream.readObject();

            String State = ServerReply.GetData();

            OutToServer.close();
            FromServerStream.close();
            
            
            if ("Exists".equals(State))
            {
                JOptionPane.showMessageDialog(this,
                "Request has been sent to " + ListUsers.getSelectedValue(),
                "Friend Request",
                 JOptionPane.PLAIN_MESSAGE);
            }
            else if ("Doesnt".equals(State))
            {
                JOptionPane.showMessageDialog(this,
                "Declined, this username does not exist on Hitify",
                "Friend Request",
                 JOptionPane.PLAIN_MESSAGE);
            }
            else if ("AlreadyFriends".equals(State))
            {
                JOptionPane.showMessageDialog(this,
                "You are already friends with this user, or they have sent you a friend request",
                "Friend Request",
                 JOptionPane.PLAIN_MESSAGE);
            }
            
            OutToServer.close();
            FromServerStream.close();
            
        } catch (IOException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cmdAddFriendActionPerformed

    public ArrayList<String> FindUsers()
    {
        ArrayList<String> AllUsers = new ArrayList();
        try {
            Socket MainServer = new Socket("localhost", 9090);

            ObjectOutputStream OutToServer = new ObjectOutputStream(MainServer.getOutputStream());
            ObjectInputStream FromServerStream = new ObjectInputStream(MainServer.getInputStream());

            InfoPacket FindUsers = new InfoPacket();
            //GET MY FRIENDS
            FindUsers.SetService("GUP");
            FindUsers.SetSingleData(cbPreference.getSelectedItem().toString());

            OutToServer.writeObject(FindUsers);

            InfoPacket ServerReply = (InfoPacket) FromServerStream.readObject();

            AllUsers = ServerReply.GetArray();

            OutToServer.close();
            FromServerStream.close();
            
            

        } catch(IOException | ClassNotFoundException e)
        {
            System.out.println(e.getMessage());
        }
        return AllUsers;
    }
    
    public void UpdateList (ArrayList<String> UserNames)
    {
        DefaultListModel Users = new DefaultListModel();       
        for (int i = 0; i < UserNames.size(); i++)
        {
            if (this.Username.equals(UserNames.get(i)))
            {
                //Do nothing. Do not enter own username to the list
            }
            else {
                Users.addElement(UserNames.get(i));
            }  
        }
        ListUsers.setModel(Users);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListUsers;
    private javax.swing.JComboBox<String> cbPreference;
    private javax.swing.JButton cmdAddFriend;
    private javax.swing.JButton cmdBackToMain;
    private javax.swing.JButton cmdFind;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
