/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testingcoursework;

import java.awt.Color;
import javax.swing.ImageIcon;
import infopacket.InfoPacket;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author samal
 */
public class RegisterUser extends javax.swing.JFrame {

    private String Filepath = "";
    
    static void SetPhoto(ImageIcon ResizeImage) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form RegisterUser
     */
    public RegisterUser() {
        initComponents();
        
        this.getContentPane().setBackground(Color.decode("#2B2D42"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lblMusicChoice1 = new javax.swing.JLabel();
        lblRegisterNewUser = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblSecondName = new javax.swing.JLabel();
        txtSecondName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblPassword2 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JTextField();
        lblMusicChoice = new javax.swing.JLabel();
        rbFolk = new javax.swing.JRadioButton();
        rbRock = new javax.swing.JRadioButton();
        rbTechno = new javax.swing.JRadioButton();
        rbSoul = new javax.swing.JRadioButton();
        rbPop = new javax.swing.JRadioButton();
        rbBlues = new javax.swing.JRadioButton();
        rbJazz = new javax.swing.JRadioButton();
        rbReggae = new javax.swing.JRadioButton();
        rbEDM = new javax.swing.JRadioButton();
        rbRapping = new javax.swing.JRadioButton();
        rbIndie = new javax.swing.JRadioButton();
        rbClassical = new javax.swing.JRadioButton();
        lblUploadPicture = new javax.swing.JLabel();
        cmdPhoto = new javax.swing.JButton();
        cmdCreate = new javax.swing.JButton();
        cmdLogIn = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        lblMusicChoice1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMusicChoice1.setText("Select Music Interests:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 45, 66));

        lblRegisterNewUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRegisterNewUser.setText("Register New User");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setText("First Name:");

        lblSecondName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSecondName.setText("Second Name:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email Address:");

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserName.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblPassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword2.setText("Confirm Password:");

        lblMusicChoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMusicChoice.setText("Select Music Interests:");

        rbFolk.setText("Folk");

        rbRock.setText("Rock");

        rbTechno.setText("Techno");

        rbSoul.setText("Soul");

        rbPop.setText("Pop");

        rbBlues.setText("Blues");
        rbBlues.setToolTipText("");

        rbJazz.setText("Jazz");

        rbReggae.setText("Reggae");

        rbEDM.setText("EDM");

        rbRapping.setText("Rapping");

        rbIndie.setText("Indie");

        rbClassical.setText("Classical");

        lblUploadPicture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUploadPicture.setText("Upload Profile Picture");

        cmdPhoto.setText("Upload Photo");
        cmdPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPhotoActionPerformed(evt);
            }
        });

        cmdCreate.setText("Create New Profile");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });

        cmdLogIn.setText("Back To Log In Screen");
        cmdLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogInActionPerformed(evt);
            }
        });

        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword2)
                            .addComponent(lblPassword)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblSecondName)
                                    .addComponent(txtSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMusicChoice)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbFolk)
                                                    .addComponent(rbPop)
                                                    .addComponent(rbEDM))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbRock)
                                                    .addComponent(rbBlues)
                                                    .addComponent(rbRapping)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbSoul)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbReggae)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbClassical)
                                            .addComponent(rbJazz)
                                            .addComponent(rbTechno)
                                            .addComponent(rbIndie)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmdCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmdLogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblUploadPicture, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmdPhoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(lblRegisterNewUser)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegisterNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblMusicChoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFolk)
                    .addComponent(rbRock)
                    .addComponent(rbTechno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecondName)
                    .addComponent(rbPop)
                    .addComponent(rbBlues)
                    .addComponent(rbJazz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbEDM)
                    .addComponent(rbRapping)
                    .addComponent(rbIndie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(rbSoul)
                    .addComponent(rbReggae)
                    .addComponent(rbClassical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCreate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassword2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdLogIn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblUploadPicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdPhoto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        lblMusicChoice.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogInActionPerformed
        new LogInScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdLogInActionPerformed

    private void cmdPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPhotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        Filepath = f.getAbsolutePath();
        lblPhoto.setIcon(ResizeImage(Filepath));
        
    }//GEN-LAST:event_cmdPhotoActionPerformed

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        Boolean isValid;
        isValid = ValidChecks();
        
        if (isValid == true)
        {
            String Password = txtPassword.getText();
            String PasswordConfirm = txtPassword2.getText();
            //If password is entered correctly twice
            if (Password.equals(PasswordConfirm))
            {
                ArrayList UserRegister = new ArrayList();
                
                UserRegister.add(txtUserName.getText());
                UserRegister.add(txtPassword.getText());
                UserRegister.add(txtFirstName.getText());
                UserRegister.add(txtSecondName.getText());
                UserRegister.add(txtEmail.getText());
                
                
                if (rbFolk.isSelected()) UserRegister.add("Folk");
                if (rbRock.isSelected()) UserRegister.add("Rock");
                if (rbTechno.isSelected()) UserRegister.add("Techno");
                if (rbPop.isSelected()) UserRegister.add("Pop");
                if (rbBlues.isSelected()) UserRegister.add("Blues");
                if (rbJazz.isSelected()) UserRegister.add("Jazz");
                if (rbEDM.isSelected()) UserRegister.add("EDM");
                if (rbRapping.isSelected()) UserRegister.add("Rapping");
                if (rbIndie.isSelected()) UserRegister.add("Indie");
                if (rbSoul.isSelected()) UserRegister.add("Soul");
                if (rbReggae.isSelected()) UserRegister.add("Reggae");
                if (rbClassical.isSelected()) UserRegister.add("Classical");
                
                //Get file path from file chooser               
                
                try {
                    FileInputStream UserPicture = new FileInputStream(Filepath);
                    byte [] buffer = new byte[UserPicture.available()];
                    UserPicture.read(buffer);
                    
                    Socket MainServer = new Socket("localhost", 9090);
                    
                    ObjectOutputStream OutToServer = new ObjectOutputStream(MainServer.getOutputStream());
                    
                    InfoPacket UserDetails = new InfoPacket();
                    
                    UserDetails.SetService("CNU");
                    UserDetails.SetArray(UserRegister);
                    UserDetails.SetFirstByte(buffer);
                    
                    OutToServer.writeObject(UserDetails);

                    OutToServer.close();

                    MainServer.close();

                    
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            else
            {
                //error message
            }
        }
        else
        {
            //error message
        }
        
        
        
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new UploadSong("Smilward").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private Boolean ValidChecks() {
        
        if (txtFirstName.getText().length() < 2 || txtSecondName.getText().length() < 2)
        {
            return false;
        }
        else if(txtEmail.getText().length() < 5 || txtUserName.getText().length() < 5)
        {
            return false;
        }
        else if (txtPassword.getText().length() < 3)
        {
            return false;
        }
        //if email does not contain a "@" or "."
        else if (txtEmail.getText().contains("@") == false || txtEmail.getText().contains(".") == false)
        {
            return false;
        }
        else if (txtUserName.getText().length() < 5)
        {
            return false;
        }
        
        int PrefCounter = 0;
        
        if (rbFolk.isSelected()) PrefCounter++;
        if (rbRock.isSelected()) PrefCounter++;
        if (rbTechno.isSelected()) PrefCounter++;
        if (rbPop.isSelected()) PrefCounter++;
        if (rbBlues.isSelected()) PrefCounter++;
        if (rbJazz.isSelected()) PrefCounter++;
        if (rbEDM.isSelected()) PrefCounter++;
        if (rbRapping.isSelected()) PrefCounter++;
        if (rbIndie.isSelected()) PrefCounter++;
        if (rbSoul.isSelected()) PrefCounter++;
        if (rbReggae.isSelected()) PrefCounter++;
        if (rbClassical.isSelected()) PrefCounter++;
        
        if (PrefCounter < 1)
        {
            System.out.println("Please select at least one music prefernce");
            
            return false;
        }
        
        if ("".equals(Filepath))
        {
            System.out.println("Please select a profile picture");
            return false;
        }
        
        return true;
    }
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton cmdCreate;
    private javax.swing.JButton cmdLogIn;
    private javax.swing.JButton cmdPhoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblMusicChoice;
    private javax.swing.JLabel lblMusicChoice1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblRegisterNewUser;
    private javax.swing.JLabel lblSecondName;
    private javax.swing.JLabel lblUploadPicture;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JRadioButton rbBlues;
    private javax.swing.JRadioButton rbClassical;
    private javax.swing.JRadioButton rbEDM;
    private javax.swing.JRadioButton rbFolk;
    private javax.swing.JRadioButton rbIndie;
    private javax.swing.JRadioButton rbJazz;
    private javax.swing.JRadioButton rbPop;
    private javax.swing.JRadioButton rbRapping;
    private javax.swing.JRadioButton rbReggae;
    private javax.swing.JRadioButton rbRock;
    private javax.swing.JRadioButton rbSoul;
    private javax.swing.JRadioButton rbTechno;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword2;
    private javax.swing.JTextField txtSecondName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
